### ISSUE TITLE
ESP8266 Support

### ISSUE THREAD

**Issue by whopiyush** [dmazzella/ucryptography#4]
Hello! Thank you for your work on the library! 

I was trying to use the library with my ESP8266, I tried compiling it, but after flashing it did not show up in the modules in micropython. I used the ESP32 build commands as references, but I don't think it is supported it. Are there any plans to support ESP8266?

this is the command I used to build the firmware - ` make -C ports/esp8266 BOARD=ESP8266_GENERIC USER_C_MODULES="$(pwd)/usercmodule/ucryptography/micropython.cmake"`

Also, the patch file seems to be outdated now, so the patch was not applied, so instead, I manually added the constants to the file

**Comment by dmazzella** [comment]
Hello, 
can you send me the output of the compilation? are there any warnings? errors?

**Comment by dmazzella** [comment]
please read steps from MicroPython ports/esp8266 README.md [Building with a local toolchain](https://github.com/micropython/micropython/tree/master/ports/esp8266)

**Comment by dmazzella** [comment]
for now I am closing as unsupported platform, ucryptography needs mbedtls at version 3, and esp8266 uses axtls

**Comment by whopiyush** [comment]
Hello!

>  can you send me the output of the compilation? are there any warnings? errors?

There were no errors, it compiles successfully, but the module was not getting added, makes sense now

> please read steps from MicroPython ports/esp8266 README.md [Building with a local toolchain](https://github.com/micropython/micropython/tree/master/ports/esp8266?rgh-link-date=2024-08-29T08%3A25%3A10Z)

Yes, this is what I followed to build from scratch, just modified the make command to include the makefile for ucryptography

> for now I am closing as unsupported platform, ucryptography needs mbedtls at version 3, and esp8266 uses axtls

Oh I see, that's sad, thank you anyway!

Could you please update the patchfile if possible, it seems like the source file was edited causing patch to fail, attached the screenshot (I manually patch the file now)

![image](https://github.com/user-attachments/assets/168d0e9e-fd6d-4f1f-98fa-f93e268c118b)

**Comment by dmazzella** [comment]
> Could you please update the patchfile if possible, it seems like the source file was edited causing patch to fail, attached the screenshot (I manually patch the file now)

Done, thank you
