### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by m4verick84** [dmazzella/ucryptography#7]
Hi,

tried to compile it for an rp2 board (W5500_EVB_PICO), but received the following error:

ucryptography/modcryptography.c:114:10: fatal error: rsa_alt_helpers.h: No such file or directory

I've built it in fedora. Maybe fedora is using an outdated mbedtls? 

Many thanks,
bye

**Comment by dmazzella** [comment]
rp2 is not a supported platform at this time.
ucryptography uses as interfaces those of mbedtls 3.x while rp2 uses mbedtls 2.x

[pico-sdk mbedtls](https://github.com/raspberrypi/pico-sdk/tree/efe2103f9b28458a1615ff096054479743ade236/lib)

**Comment by m4verick84** [comment]
Thanks for the fast response. I've noticed that it is version related, but i haven't checked the path of the build files ... Thought it was maybe distribution related. Anyway, the issue is resolved. Thanks!
